### ISSUE TITLE
Confidential information appears in warehouse records

### ISSUE THREAD

**Issue by JulyFinal** [pypi-data/pypi-code#1]
@orf 

Hi, I found out that some confidential information from our company was accidentally uploaded to PyPi and today we found out that this information was accidentally scanned by you.

Thank you very much for your help in finding out about the confidential leak.

However, I still need to ask for your help to delete the information left in this repository. Could you please remove all relevant information contained in the package "chtool"?

Thank you.

**Comment by JulyFinal** [comment]
> @orf
> 
> Hi, I found out that some confidential information from our company was accidentally uploaded to PyPi and today we found out that this information was accidentally scanned by you.
> 
> Thank you very much for your help in finding out about the confidential leak.
> 
> However, I still need to ask for your help to delete the information left in this repository. Could you please remove all relevant information contained in the package "chtool"?
> 
> Thank you.

I also need your help in removing all relevant information from the history of commit.

https://github.com/pypi-data/pypi-code/tree/b51a4f7312b19f7a8868993c1459a623f1cde10e/code/chtool

Thank you very much.

**Comment by orf** [comment]
Hello,
This project is still available on PyPi (https://pypi.org/project/chtool/#history) and the database credentials in the code have been available there for over 3 years.

I am very happy that my work has helped identify leaker credentials, but my position on this is twofold:
1. The code is still downloadable from pypi ([for example from this direct url](https://files.pythonhosted.org/packages/e8/42/d3a6a5f7e837e2dfd56827d8003ce036d9da629aeae5670f4b7461e28ac4/chtool-0.0.2.tar.gz)), even after a release is deleted.
2. Removing the code here gives a false sense of security: the contents of this package is thoroughly distributed via mirrors, scanners and other systems. Attempting by any means to undo that is fruitless.

**Comment by JulyFinal** [comment]
> 

You are right, we have started contacting the parties involved and PyPi officials to try to remove the codes as soon as we received the report. We are still waiting for the results, But I don't know how long it will take. We can only try to eliminate all the codes found so far.

We are trying all the ways to make up for the mistakes that occurred before.

Thank you for your prompt reply.
